//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shwet_Shiva_Printing_Services_and_Mrityunjay_Mudranalay
{


    public partial class Cart
    {
    }
}
